language: cpp
compiler:
  - gcc
env:
  # These are used by .travis-cmake.sh to set a configuration
  - CMS_CONFIG=NORMAL
#  - CMS_CONFIG=STATIC_BIN
  - CMS_CONFIG=SIMPLE
#  - CMS_CONFIG=SIMPLE_STATIC
  - CMS_CONFIG=MORE_DEBUG
  - CMS_CONFIG=NOSTATS
  - CMS_CONFIG=NOZLIB
  - CMS_CONFIG=RELEASE
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
install:
  - sudo apt-get install libboost-program-options-dev libboost-test-dev gcc-4.7 g++-4.7
  - sudo apt-get install cmake
  - sudo pip install lit
#
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
script:
#  - CC="gcc-4.7" CXX="g++-4.7" cmake -DENABLE_TESTING=ON ..
  - ../.travis-cmake.sh ../
  - make
  - ctest -V
  - sudo make install
