language: cpp
cache: ccache

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty

# not container-based
sudo: required

env:
  global:
    - secure: SodOHkeIggfLhzWD2kxbmHWcbqhOZzL5/5RFxUH+wPtj4VArxeTWCklSAn5BjrSZN9ljVf+lArt4L238odotLhCa9UXjvuPOFVQ+nAGw7XNjso/ccu1ce9cClv+Dzlc8NVJx0tApGZqJjscYesfw/Ij2fN21iwk/U736E08ya9I=
    - secure: "iWvQPW/6x5CM0rxK37gdbGBbjr2EhVeTPlWT9AfM9mXOnRz76ANq3O4xVmBw0KbfLExBOu8wNyzDf07NMBWzKNyyj0fBWzLVoToLF/R9PYkiiqYT2DWtT/iawf3uXhQKMUN9zfQNULtN6DrWIZXpBkHRDuQjNkNu6mXExkFdEcc="
  matrix:
    - CMS_CONFIG=NORMAL
    - CMS_CONFIG=LARGEMEM
    - CMS_CONFIG=LARGEMEM_GAUSS
    - CMS_CONFIG=ONLY_SIMPLE
    - CMS_CONFIG=STATS
    - CMS_CONFIG=NOZLIB
    - CMS_CONFIG=RELEASE
    - CMS_CONFIG=NOSQLITE
    - CMS_CONFIG=NOPYTHON
    - CMS_CONFIG=SQLITE
    - CMS_CONFIG=M4RI
    - CMS_CONFIG=IPASIR_M4RI
#    - CMS_CONFIG=WEB
    - CMS_CONFIG=GAUSS
    - CMS_CONFIG=COVERAGE
    - CMS_CONFIG=SLOW_DEBUG
    - CMS_CONFIG=INTREE_BUILD
    - CMS_CONFIG=NOTEST
    - CMS_CONFIG=STATIC
    - CMS_CONFIG=ONLY_SIMPLE_STATIC

matrix:
  include:
    # Covertiy scan should only run once
    - os: linux
      compiler: gcc
      env: COVERITY_SCAN=1 CMS_CONFIG=NORMAL

  # COVERAGE scan should only run once
  exclude:
    - os: linux
      compiler: clang
      env: CMS_CONFIG=COVERAGE

  allow_failures:
    # Covertiy scan might fail
    - env: COVERITY_SCAN=1 CMS_CONFIG=NORMAL

addons:
  coverity_scan:
    project:
      name: "msoos/cryptominisat"
      description: "Advanced SAT solver"
    notification_email: soos.mate@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install libboost cmake valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --force-yes libboost-test-dev valgrind; fi

install:
#cmake
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure > cmake_config_out.txt
  - make -j2 > cmake_build_out.txt
  - sudo make install > cmake_install_out.txt
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cmake --version
  - cd ..
#coveralls
  - sudo pip install cpp-coveralls
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
#lingeling
  - git clone https://github.com/msoos/lingeling-ala
  - cd lingeling-ala
  - ./configure
  - make
  - sudo cp lingeling /usr/local/bin/
  - cd ..
# lit
    # NOTE we probably should NOT use 'sudo' because Travis uses virtualenvs
  - sudo -H pip install --upgrade pip
  - sudo -H pip install lit
  - lit --version
  - which lit
#submodules
  - git submodule init
  - git submodule update
#bulid dir
  - mkdir -p build

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./scripts/travis-cmake.sh ; fi
