language: cpp
compiler:
  - gcc
  - clang
env:
  # These are used by .travis-cmake.sh to set a configuration
  - CMS_CONFIG=NORMAL
#  - CMS_CONFIG=STATIC_BIN
  - CMS_CONFIG=ONLY_SIMPLE
#  - CMS_CONFIG=ONLY_SIMPLE_STATIC
  - CMS_CONFIG=MORE_DEBUG
  - CMS_CONFIG=STATS
  - CMS_CONFIG=NOZLIB
  - CMS_CONFIG=RELEASE
  - CMS_CONFIG=NOSQLITE
  - CMS_CONFIG=NOMYSQL
  - CMS_CONFIG=NOMYSQLNOSQLITE
  - CMS_CONFIG=PYTHON
  - CMS_CONFIG=MYSQL
  - CMS_CONFIG=SQLITE
  - CMS_CONFIG=M4RI
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
install:
  - sudo apt-get install libboost-test-dev gcc-4.7 g++-4.7
  - sudo apt-get remove g++-4.6 gcc-4.6
  - sudo apt-get install cmake
  - sudo pip install lit
#
#get lingeling
  - git clone https://github.com/msoos/lingeling-ala
  - cd lingeling-ala
  - ./configure
  - make
  - sudo cp lingeling /usr/local/bin/
  - cd ..
#
#get drat-trim
  - git clone https://github.com/msoos/drat
  - cd drat
  - make
  - sudo cp drat-trim /usr/local/bin/
  - cd ..
#
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
script:
  - ../.travis-cmake.sh ../ build
